### ISSUE TITLE
Developer Profiles

### ISSUE THREAD

**Issue by entreprenerd24** [bradwestfall/webdevphoenix#7]
Good idea, putting this up here.

Anyhow, yeah that exactly what i'm saying, profiles for individuals to really match people who will work well together. Finding a co-founder isn't like hiring an employee it's a much more delicate process, more like dating.

**Comment by bradwestfall** [comment]
I see. I just want to pose some of my initial thoughts. Since the site is Jekyll and not a database, pull requests seems like the easiest way to add profiles on my end. It's at the expense of being more difficult for everyone else to add profiles. The company profile info we're asking for doesn't change often, but my concern is that individual profiles might change more often. What are your thoughts there?

Do you think it makes sense for one of the parties to make a profile and the other just searches without making a profile? We could incorporate a chat forum (Disqus) on the bottom of the profile for people to ask questions of the profile holder? Thoughts?

**Comment by entreprenerd24** [comment]
Oh yes that could work, we could just have the devs create one so there is
a place entre. Can go to search through a list of canidates… maybe, im
going to have to think about it.

Sorry I just have ideas, thats why I need a cofounding dev haha! Im still
learning how difficult it is to build various types of software and such.

**Comment by stevesmename** [comment]
Hey Brad, think your jekyll project is great. I was looking into the issues and found this one, it's a good thought. I personally though do not look for "co-founders" but rather developers. So as stated developer profiles could be usefull for independent contractors to be listed. Maintenance is definitely an issue but a PR could be auto-approved by middleware, sort of like a testbot. I also suggest changing the title of this issue to something like "developer profiles".

**Comment by entreprenerd24** [comment]
Thanks for the feedback steve! The problem were really trying to solve though is matching not technical people (with limited funds) with technical people so they can build a company together. 

I myself am in search for a developer, but it's a very tricky process finding the right person who fits well with who I am, and will be the right culture fit for the company I'm working on building.

**Comment by stevesmename** [comment]
Wouldn't you reach out then to developer profiles who fit your need? Just as Developers would reach out to companies listed to get hired? IMO what your looking for is just to be listed as a company profile and your company bio would grab the interest of developers.

**Comment by entreprenerd24** [comment]
Yeah, that would definitely work!

**Comment by bradwestfall** [comment]
This looks like good conversation, I'll have to catch all of it later after work

**Comment by bradwestfall** [comment]
@stevesmename Thanks for your input. I also agree that this is a broader topic about developer profiles which can incorporate co-founder seeking. I think there can be attribute about what the goals are for the developer. One goal can be interest level in partnerships / startups / co-founder-ships

How does that sound @entreprenerd24 ?

**Comment by bradwestfall** [comment]
I'd also like to get your thoughts on https://github.com/bradwestfall/webdevphoenix/issues/19

**Comment by entreprenerd24** [comment]
See I think I disagree, but that because i'm thinking about what i'm going through right now as a not technical person looking for a technical person. I would really like something where I can go and look through a bunch of profiles of people who are looking to start a company. That could be exactly what you are saying though, i'm a little confused.

**Comment by bradwestfall** [comment]
So what I mean is make developer profiles for all types of developers instead of strictly ones who are looking to be co-founders. Each developer profile can have properties stating their goals, such as `contract_work: true`, and `co-founder-okay: true`. You could then see all developers or use a filter that shows only developers who wanted co founder. This way it's a feature that serves a wider purpose

**Comment by entreprenerd24** [comment]
but isn't that pretty much what elance and odesk are for? Looking for a cofounder is completely different from looking for someone to do contracted work. Also, are you looking to add this onto your already existing project, or is this going to be started from scratch?

**Comment by bradwestfall** [comment]
I suppose it would be similar. I was coming at this conversation from adding it to the existing webdevphoenix. If what you're talking about is a whole new project then it can be anything, but with this project I think it would be a mistake to make a feature that serves such a specific need. That's why I was thinking of ways we can open it up some more, make it more general

**Comment by entreprenerd24** [comment]
ohhhhhhh, yeah I had a feeling, but wasn't sure. See I was confused when you said profile, so I was just thinking a whole new platform. My bad, then yeah, of course just adding the option of willing to be a cofounder or something along those lines would be awesome.

**Comment by bradwestfall** [comment]
Sweet, I'll get that in there then. I think it's a cool feature

**Comment by entreprenerd24** [comment]
Yeah man. it's a problem I keep hearing people business people grapple with. I myself am in search for one, and boy oh boy is it tricky. However, I have a process i've create that i'm pretty confident about, and as long as I can share my vison clearly, and inspire people then I think I'll be able to find the right people. But I need to know where they are first haha!

**Comment by bradwestfall** [comment]
So, just to make sure I understand - If we have profiles of developers on webdevphoenix, whereby some are looking for co-founders, then this would help?

**Comment by entreprenerd24** [comment]
Most definitely! And if you could add an area where they can add things they are interested in that would be really cool because then you could screen for culture fit.

**Comment by bradwestfall** [comment]
Feature added
